# Backtrader for Backtesting(Python)

## What is Backtrader 
Backtrader is a Python library that aids in strategy development and testing for traders of the financial markets.

It is an open-source framework that allows for strategy testing on historical data. Further, it can be used to optimize strategies, create visual plots, and can even be used for live trading.

there are other libraries also for backtesting like Zipline

Here are some of the things Backtrader excels at:

### Backtesting – 
This might seem like an obvious one but Backtrader removes the tedious process of cleaning up your data and iterating through it to test strategies. It has built-in templates to use for various data sources to make importing data easier.

### Optimizing –
Adjusting a few parameters can sometimes be the difference between a profitable strategy and an unprofitable one. After running a backtest, optimizing is easily done by changing a few lines of code.

### Plotting – 
If you’ve worked with a few Python plotting libraries, you’ll know these are not always easy to configure, especially the first time around. A complex chart can be created with a single line of code.

### Indicators – 
Most of the popular indicators are already programmed in the Backtrader platform. This is especially useful if you want to test out an indicator but you’re not sure how effective it will be. Rather than trying to figure out the math behind the indicator, and how to code it, you can test it out first in Backtrader, probably with one line of code.

### Support for Complex Strategies –
Want to take a signal from one dataset and execute a trade on another? Does your strategy involve multiple timeframes? Or do you need to resample data? Backtrader has accounted for the various ways traders approach the markets and has extensive support.

$Note $:- 

        Backtrader is used for backtesting and not live trading 
        QuantConnect is a browser based platform that allows both backtesting and live trading

## How Backtrader Works 
Backtrader shows you how your strategy might perform in the market by testing it against past price data.

The library’s most basic functionality is to iterate through historical data and to simulate the execution of trades based on signals given by your strategy.

It extends on this functionality in many ways. A Backtrader “analyzer” can be added to provide useful statistics. We will show an example of this using the commonly used Sharpe Ratio in a optimization test later in this tutorial.

On the subject of optimization, it’s clear a lot of thought has been put in to speeding up the testing of strategies with different parameters. The built in optimization module uses multiprocessing, fully utilizing your multiple CPU cores to speed up the process.

Lastly, Backtrader utilizes the well-known matplotlib library to create charts at the end of your backtest, if desired.

## How to configure the basic Bactrader Setup

In [1]:
import backtrader as bt

In [2]:
class MyStrategy(bt.Strategy):
    def next(self):
        pass # Do Something 

# initiate Cerebro engine 
cerebro = bt.Cerebro()

# Add Strategy to Cerebro 
cerebro.addstrategy(MyStrategy)

# Run the Cerebro Engine
cerebro.run()

[]

We will go into the strategy class in more detail in the examples that follow. This is where all the logic goes in determining and executing your trade signals. It is also where indicators can be created or called, and where you can determine what get’s logged or printed to screen.

The cerebro engine is the core of Backtrader. This is the main class and we will add our data and strategies to it before eventually calling the cerebro.run() command.

## Adding the data and import it to Backtrader

I will be using yfinance library to get the data

In [3]:
import yfinance as yf 
import datetime as dt

In [4]:
start = dt.datetime(2023,1,1)
end = dt.datetime(2026,1,1)
data = yf.download('TSLA',start,end)
data.columns = data.columns.droplevel(1)

[*********************100%***********************]  1 of 1 completed

In [5]:
data.to_csv('TSLA.csv')

In [6]:
data = bt.feeds.YahooFinanceCSV(dataname='TSLA.csv')
# cerebro.addata(data) for adding data to cerebro

In the above example, we’ve assigned the CSV dataset to a variable named data. The next step is to add this to cerebro.

Adding data can be done at any point between instantiating cerebro and calling the cerebro.run() command. There are several additional parameters we can specify when loading our data. We will explore this further in our next example

» Here are some (mostly) free data sources and guides:

* Quandl: A Step-by-Step Guide
* Google Finance API and 9 Alternatives
* Yahoo Finance API – A Complete Guide

## How to print or log data using the strategy class in Backtrader

### In the __init__ function above,
 we’ve created a variable called dataclose to make it easier to refer to the closing price later on. You will notice that the closing price is stored in datas[0].close. We can just as easily access the open price by referencing datas[0].open

An important feature of Backtrader is accessing historical data which we can now do via the dataclose variable. As Backtrader iterates through historical data, this variable will get updated with the latest price from dataclose[0]. We can also look back to the prior data points by accessing the negative index of dataclose. Here is an example.

if dataclose[0] > dataclose [-1]: pass # do something

The above code checks to see if the most recent close is larger than the prior close. We can just as easily access the second last closing price by changing the index like this: dataclose[-2]

In [7]:
class PrintClose(bt.Strategy):
    """The log function allows us to pass in data via the txt variable that we want to output to the screen. It will attempt to grab datetime values from the most recent data point,if available, and log it to the screen"""
    def log(self, txt , dt=None):
        dt = dt or self.datas[0].datetime.date(0)
        print(dt.isoformat(), txt) # print date and close
    def __init__(self):
        self.dataclose = self.datas[0].close
    def next(self):
        self.log(f'Close:{self.dataclose[0]}')

cerebro = bt.Cerebro()
# there is an issue with this since modern csvs data don't have adj Close columns but YahooFinanceCsvdata function assumes it still exists therefore its returning Volume instead of Closing price 
# data = bt.feeds.YahooFinanceCSVData(dataname='TSLA.csv')
data = bt.feeds.GenericCSVData(
    dataname='TSLA.csv',
    
    dtformat='%Y-%m-%d', # Ensure this matches the date format in your CSV (e.g., YYYY-MM-DD)
    
    datetime=0,
    open=4,
    high=2,
    low=3,
    close=1,
    volume=5,
    
    openinterest=-1, # -1 tells Backtrader this column doesn't exist in your CSV
    headers=True     # Assumes the first row of your CSV is the header (Date, Open, etc.)
)
cerebro.adddata(data)

cerebro.addstrategy(PrintClose)

cerebro.run()

2023-01-03 Close:108.0999984741211
2023-01-04 Close:113.63999938964844
2023-01-05 Close:110.33999633789062
2023-01-06 Close:113.05999755859375
2023-01-09 Close:119.7699966430664
2023-01-10 Close:118.8499984741211
2023-01-11 Close:123.22000122070312
2023-01-12 Close:123.55999755859375
2023-01-13 Close:122.4000015258789
2023-01-17 Close:131.49000549316406
2023-01-18 Close:128.77999877929688
2023-01-19 Close:127.16999816894531
2023-01-20 Close:133.4199981689453
2023-01-23 Close:143.75
2023-01-24 Close:143.88999938964844
2023-01-25 Close:144.42999267578125
2023-01-26 Close:160.27000427246094
2023-01-27 Close:177.89999389648438
2023-01-30 Close:166.66000366210938
2023-01-31 Close:173.22000122070312
2023-02-01 Close:181.41000366210938
2023-02-02 Close:188.27000427246094
2023-02-03 Close:189.97999572753906
2023-02-06 Close:194.75999450683594
2023-02-07 Close:196.80999755859375
2023-02-08 Close:201.2899932861328
2023-02-09 Close:207.32000732421875
2023-02-10 Close:196.88999938964844
2023-02-13 Close:194.63999938964844
2023-02-14 Close:209.25
2023-02-15 Close:214.24000549316406
2023-02-16 Close:202.0399932861328
2023-02-17 Close:208.30999755859375
2023-02-21 Close:197.3699951171875
2023-02-22 Close:200.86000061035156
2023-02-23 Close:202.07000732421875
2023-02-24 Close:196.8800048828125
2023-02-27 Close:207.6300048828125
2023-02-28 Close:205.7100067138672
2023-03-01 Close:202.77000427246094
2023-03-02 Close:190.89999389648438
2023-03-03 Close:197.7899932861328
2023-03-06 Close:193.80999755859375
2023-03-07 Close:187.7100067138672
2023-03-08 Close:182.0
2023-03-09 Close:172.9199981689453
2023-03-10 Close:173.44000244140625
2023-03-13 Close:174.47999572753906
2023-03-14 Close:183.25999450683594
2023-03-15 Close:180.4499969482422
2023-03-16 Close:184.1300048828125
2023-03-17 Close:180.1300048828125
2023-03-20 Close:183.25
2023-03-21 Close:197.5800018310547
2023-03-22 Close:191.14999389648438
2023-03-23 Close:192.22000122070312
2023-03-24 Close:190.41000366210938
2023-03-27 Close:191.80999755859375
2023-03-28 Close:189.19000244140625
2023-03-29 Close:193.8800048828125
2023-03-30 Close:195.27999877929688
2023-03-31 Close:207.4600067138672
2023-04-03 Close:194.77000427246094
2023-04-04 Close:192.5800018310547
2023-04-05 Close:185.52000427246094
2023-04-06 Close:185.05999755859375
2023-04-10 Close:184.50999450683594
2023-04-11 Close:186.7899932861328
2023-04-12 Close:180.5399932861328
2023-04-13 Close:185.89999389648438
2023-04-14 Close:185.0
2023-04-17 Close:187.0399932861328
2023-04-18 Close:184.30999755859375
2023-04-19 Close:180.58999633789062
2023-04-20 Close:162.99000549316406
2023-04-21 Close:165.0800018310547
2023-04-24 Close:162.5500030517578
2023-04-25 Close:160.6699981689453
2023-04-26 Close:153.75
2023-04-27 Close:160.19000244140625
2023-04-28 Close:164.30999755859375
2023-05-01 Close:161.8300018310547
2023-05-02 Close:160.30999755859375
2023-05-03 Close:160.61000061035156
2023-05-04 Close:161.1999969482422
2023-05-05 Close:170.05999755859375
2023-05-08 Close:171.7899932861328
2023-05-09 Close:169.14999389648438
2023-05-10 Close:168.5399932861328
2023-05-11 Close:172.0800018310547
2023-05-12 Close:167.97999572753906
2023-05-15 Close:166.35000610351562
2023-05-16 Close:166.52000427246094
2023-05-17 Close:173.86000061035156
2023-05-18 Close:176.88999938964844
2023-05-19 Close:180.13999938964844
2023-05-22 Close:188.8699951171875
2023-05-23 Close:185.77000427246094
2023-05-24 Close:182.89999389648438
2023-05-25 Close:184.47000122070312
2023-05-26 Close:193.1699981689453
2023-05-30 Close:201.16000366210938
2023-05-31 Close:203.92999267578125
2023-06-01 Close:207.52000427246094
2023-06-02 Close:213.97000122070312
2023-06-05 Close:217.61000061035156
2023-06-06 Close:221.30999755859375
2023-06-07 Close:224.57000732421875
2023-06-08 Close:234.86000061035156
2023-06-09 Close:244.39999389648438
2023-06-12 Close:249.8300018310547
2023-06-13 Close:258.7099914550781
2023-06-14 Close:256.7900085449219
2023-06-15 Close:255.89999389648438
2023-06-16 Close:260.5400085449219
2023-06-20 Close:274.45001220703125
2023-06-21 Close:259.4599914550781
2023-06-22 Close:264.6099853515625
2023-06-23 Close:256.6000061035156
2023-06-26 Close:241.0500030517578
2023-06-27 Close:250.2100067138672
2023-06-28 Close:256.239990234375
2023-06-29 Close:257.5
2023-06-30 Close:261.7699890136719
2023-07-03 Close:279.82000732421875
2023-07-05 Close:282.4800109863281
2023-07-06 Close:276.5400085449219
2023-07-07 Close:274.42999267578125
2023-07-10 Close:269.6099853515625
2023-07-11 Close:269.7900085449219
2023-07-12 Close:271.989990234375
2023-07-13 Close:277.8999938964844
2023-07-14 Close:281.3800048828125
2023-07-17 Close:290.3800048828125
2023-07-18 Close:293.3399963378906
2023-07-19 Close:291.260009765625
2023-07-20 Close:262.8999938964844
2023-07-21 Close:260.0199890136719
2023-07-24 Close:269.05999755859375
2023-07-25 Close:265.2799987792969
2023-07-26 Close:264.3500061035156
2023-07-27 Close:255.7100067138672
2023-07-28 Close:266.44000244140625
2023-07-31 Close:267.42999267578125
2023-08-01 Close:261.07000732421875
2023-08-02 Close:254.11000061035156
2023-08-03 Close:259.32000732421875
2023-08-04 Close:253.86000061035156
2023-08-07 Close:251.4499969482422
2023-08-08 Close:249.6999969482422
2023-08-09 Close:242.19000244140625
2023-08-10 Close:245.33999633789062
2023-08-11 Close:242.64999389648438
2023-08-14 Close:239.75999450683594
2023-08-15 Close:232.9600067138672
2023-08-16 Close:225.60000610351562
2023-08-17 Close:219.22000122070312
2023-08-18 Close:215.49000549316406
2023-08-21 Close:231.27999877929688
2023-08-22 Close:233.19000244140625
2023-08-23 Close:236.86000061035156
2023-08-24 Close:230.0399932861328
2023-08-25 Close:238.58999633789062
2023-08-28 Close:238.82000732421875
2023-08-29 Close:257.17999267578125
2023-08-30 Close:256.8999938964844
2023-08-31 Close:258.0799865722656
2023-09-01 Close:245.00999450683594
2023-09-05 Close:256.489990234375
2023-09-06 Close:251.9199981689453
2023-09-07 Close:251.49000549316406
2023-09-08 Close:248.5
2023-09-11 Close:273.5799865722656
2023-09-12 Close:267.4800109863281
2023-09-13 Close:271.29998779296875
2023-09-14 Close:276.0400085449219
2023-09-15 Close:274.3900146484375
2023-09-18 Close:265.2799987792969
2023-09-19 Close:266.5
2023-09-20 Close:262.5899963378906
2023-09-21 Close:255.6999969482422
2023-09-22 Close:244.8800048828125
2023-09-25 Close:246.99000549316406
2023-09-26 Close:244.1199951171875
2023-09-27 Close:240.5
2023-09-28 Close:246.3800048828125
2023-09-29 Close:250.22000122070312
2023-10-02 Close:251.60000610351562
2023-10-03 Close:246.52999877929688
2023-10-04 Close:261.1600036621094
2023-10-05 Close:260.04998779296875
2023-10-06 Close:260.5299987792969
2023-10-09 Close:259.6700134277344
2023-10-10 Close:263.6199951171875
2023-10-11 Close:262.989990234375
2023-10-12 Close:258.8699951171875
2023-10-13 Close:251.1199951171875
2023-10-16 Close:253.9199981689453
2023-10-17 Close:254.85000610351562
2023-10-18 Close:242.67999267578125
2023-10-19 Close:220.11000061035156
2023-10-20 Close:211.99000549316406
2023-10-23 Close:212.0800018310547
2023-10-24 Close:216.52000427246094
2023-10-25 Close:212.4199981689453
2023-10-26 Close:205.75999450683594
2023-10-27 Close:207.3000030517578
2023-10-30 Close:197.36000061035156
2023-10-31 Close:200.83999633789062
2023-11-01 Close:205.66000366210938
2023-11-02 Close:218.50999450683594
2023-11-03 Close:219.9600067138672
2023-11-06 Close:219.27000427246094
2023-11-07 Close:222.17999267578125
2023-11-08 Close:222.11000061035156
2023-11-09 Close:209.97999572753906
2023-11-10 Close:214.64999389648438
2023-11-13 Close:223.7100067138672
2023-11-14 Close:237.41000366210938
2023-11-15 Close:242.83999633789062
2023-11-16 Close:233.58999633789062
2023-11-17 Close:234.3000030517578
2023-11-20 Close:235.60000610351562
2023-11-21 Close:241.1999969482422
2023-11-22 Close:234.2100067138672
2023-11-24 Close:235.4499969482422
2023-11-27 Close:236.0800018310547
2023-11-28 Close:246.72000122070312
2023-11-29 Close:244.13999938964844
2023-11-30 Close:240.0800018310547
2023-12-01 Close:238.8300018310547
2023-12-04 Close:235.5800018310547
2023-12-05 Close:238.72000122070312
2023-12-06 Close:239.3699951171875
2023-12-07 Close:242.63999938964844
2023-12-08 Close:243.83999633789062
2023-12-11 Close:239.74000549316406
2023-12-12 Close:237.00999450683594
2023-12-13 Close:239.2899932861328
2023-12-14 Close:251.0500030517578
2023-12-15 Close:253.5
2023-12-18 Close:252.0800018310547
2023-12-19 Close:257.2200012207031
2023-12-20 Close:247.13999938964844
2023-12-21 Close:254.5
2023-12-22 Close:252.5399932861328
2023-12-26 Close:256.6099853515625
2023-12-27 Close:261.44000244140625
2023-12-28 Close:253.17999267578125
2023-12-29 Close:248.47999572753906
2024-01-02 Close:248.4199981689453
2024-01-03 Close:238.4499969482422
2024-01-04 Close:237.92999267578125
2024-01-05 Close:237.49000549316406
2024-01-08 Close:240.4499969482422
2024-01-09 Close:234.9600067138672
2024-01-10 Close:233.94000244140625
2024-01-11 Close:227.22000122070312
2024-01-12 Close:218.88999938964844
2024-01-16 Close:219.91000366210938
2024-01-17 Close:215.5500030517578
2024-01-18 Close:211.8800048828125
2024-01-19 Close:212.19000244140625
2024-01-22 Close:208.8000030517578
2024-01-23 Close:209.13999938964844
2024-01-24 Close:207.8300018310547
2024-01-25 Close:182.6300048828125
2024-01-26 Close:183.25
2024-01-29 Close:190.92999267578125
2024-01-30 Close:191.58999633789062
2024-01-31 Close:187.2899932861328
2024-02-01 Close:188.86000061035156
2024-02-02 Close:187.91000366210938
2024-02-05 Close:181.05999755859375
2024-02-06 Close:185.10000610351562
2024-02-07 Close:187.5800018310547
2024-02-08 Close:189.55999755859375
2024-02-09 Close:193.57000732421875
2024-02-12 Close:188.1300048828125
2024-02-13 Close:184.02000427246094
2024-02-14 Close:188.7100067138672
2024-02-15 Close:200.4499969482422
2024-02-16 Close:199.9499969482422
2024-02-20 Close:193.75999450683594
2024-02-21 Close:194.77000427246094
2024-02-22 Close:197.41000366210938
2024-02-23 Close:191.97000122070312
2024-02-26 Close:199.39999389648438
2024-02-27 Close:199.72999572753906
2024-02-28 Close:202.0399932861328
2024-02-29 Close:201.8800048828125
2024-03-01 Close:202.63999938964844
2024-03-04 Close:188.13999938964844
2024-03-05 Close:180.74000549316406
2024-03-06 Close:176.5399932861328
2024-03-07 Close:178.64999389648438
2024-03-08 Close:175.33999633789062
2024-03-11 Close:177.77000427246094
2024-03-12 Close:177.5399932861328
2024-03-13 Close:169.47999572753906
2024-03-14 Close:162.5
2024-03-15 Close:163.57000732421875
2024-03-18 Close:173.8000030517578
2024-03-19 Close:171.32000732421875
2024-03-20 Close:175.66000366210938
2024-03-21 Close:172.82000732421875
2024-03-22 Close:170.8300018310547
2024-03-25 Close:172.6300048828125
2024-03-26 Close:177.6699981689453
2024-03-27 Close:179.8300018310547
2024-03-28 Close:175.7899932861328
2024-04-01 Close:175.22000122070312
2024-04-02 Close:166.6300048828125
2024-04-03 Close:168.3800048828125
2024-04-04 Close:171.11000061035156
2024-04-05 Close:164.89999389648438
2024-04-08 Close:172.97999572753906
2024-04-09 Close:176.8800048828125
2024-04-10 Close:171.75999450683594
2024-04-11 Close:174.60000610351562
2024-04-12 Close:171.0500030517578
2024-04-15 Close:161.47999572753906
2024-04-16 Close:157.11000061035156
2024-04-17 Close:155.4499969482422
2024-04-18 Close:149.92999267578125
2024-04-19 Close:147.0500030517578
2024-04-22 Close:142.0500030517578
2024-04-23 Close:144.67999267578125
2024-04-24 Close:162.1300048828125
2024-04-25 Close:170.17999267578125
2024-04-26 Close:168.2899932861328
2024-04-29 Close:194.0500030517578
2024-04-30 Close:183.27999877929688
2024-05-01 Close:179.99000549316406
2024-05-02 Close:180.00999450683594
2024-05-03 Close:181.19000244140625
2024-05-06 Close:184.75999450683594
2024-05-07 Close:177.80999755859375
2024-05-08 Close:174.72000122070312
2024-05-09 Close:171.97000122070312
2024-05-10 Close:168.47000122070312
2024-05-13 Close:171.88999938964844
2024-05-14 Close:177.5500030517578
2024-05-15 Close:173.99000549316406
2024-05-16 Close:174.83999633789062
2024-05-17 Close:177.4600067138672
2024-05-20 Close:174.9499969482422
2024-05-21 Close:186.60000610351562
2024-05-22 Close:180.11000061035156
2024-05-23 Close:173.74000549316406
2024-05-24 Close:179.24000549316406
2024-05-28 Close:176.75
2024-05-29 Close:176.19000244140625
2024-05-30 Close:178.7899932861328
2024-05-31 Close:178.0800018310547
2024-06-03 Close:176.2899932861328
2024-06-04 Close:174.77000427246094
2024-06-05 Close:175.0
2024-06-06 Close:177.94000244140625
2024-06-07 Close:177.47999572753906
2024-06-10 Close:173.7899932861328
2024-06-11 Close:170.66000366210938
2024-06-12 Close:177.2899932861328
2024-06-13 Close:182.47000122070312
2024-06-14 Close:178.00999450683594
2024-06-17 Close:187.44000244140625
2024-06-18 Close:184.86000061035156
2024-06-20 Close:181.57000732421875
2024-06-21 Close:183.00999450683594
2024-06-24 Close:182.5800018310547
2024-06-25 Close:187.35000610351562
2024-06-26 Close:196.3699951171875
2024-06-27 Close:197.4199981689453
2024-06-28 Close:197.8800048828125
2024-07-01 Close:209.86000061035156
2024-07-02 Close:231.25999450683594
2024-07-03 Close:246.38999938964844
2024-07-05 Close:251.52000427246094
2024-07-08 Close:252.94000244140625
2024-07-09 Close:262.3299865722656
2024-07-10 Close:263.260009765625
2024-07-11 Close:241.02999877929688
2024-07-12 Close:248.22999572753906
2024-07-15 Close:252.63999938964844
2024-07-16 Close:256.55999755859375
2024-07-17 Close:248.5
2024-07-18 Close:249.22999572753906
2024-07-19 Close:239.1999969482422
2024-07-22 Close:251.50999450683594
2024-07-23 Close:246.3800048828125
2024-07-24 Close:215.99000549316406
2024-07-25 Close:220.25
2024-07-26 Close:219.8000030517578
2024-07-29 Close:232.10000610351562
2024-07-30 Close:222.6199951171875
2024-07-31 Close:232.07000732421875
2024-08-01 Close:216.86000061035156
2024-08-02 Close:207.6699981689453
2024-08-05 Close:198.8800048828125
2024-08-06 Close:200.63999938964844
2024-08-07 Close:191.75999450683594
2024-08-08 Close:198.83999633789062
2024-08-09 Close:200.0
2024-08-12 Close:197.49000549316406
2024-08-13 Close:207.8300018310547
2024-08-14 Close:201.3800048828125
2024-08-15 Close:214.13999938964844
2024-08-16 Close:216.1199951171875
2024-08-19 Close:222.72000122070312
2024-08-20 Close:221.10000610351562
2024-08-21 Close:223.27000427246094
2024-08-22 Close:210.66000366210938
2024-08-23 Close:220.32000732421875
2024-08-26 Close:213.2100067138672
2024-08-27 Close:209.2100067138672
2024-08-28 Close:205.75
2024-08-29 Close:206.27999877929688
2024-08-30 Close:214.11000061035156
2024-09-03 Close:210.60000610351562
2024-09-04 Close:219.41000366210938
2024-09-05 Close:230.1699981689453
2024-09-06 Close:210.72999572753906
2024-09-09 Close:216.27000427246094
2024-09-10 Close:226.1699981689453
2024-09-11 Close:228.1300048828125
2024-09-12 Close:229.80999755859375
2024-09-13 Close:230.2899932861328
2024-09-16 Close:226.77999877929688
2024-09-17 Close:227.8699951171875
2024-09-18 Close:227.1999969482422
2024-09-19 Close:243.9199981689453
2024-09-20 Close:238.25
2024-09-23 Close:250.0
2024-09-24 Close:254.27000427246094
2024-09-25 Close:257.0199890136719
2024-09-26 Close:254.22000122070312
2024-09-27 Close:260.4599914550781
2024-09-30 Close:261.6300048828125
2024-10-01 Close:258.0199890136719
2024-10-02 Close:249.02000427246094
2024-10-03 Close:240.66000366210938
2024-10-04 Close:250.0800018310547
2024-10-07 Close:240.8300018310547
2024-10-08 Close:244.5
2024-10-09 Close:241.0500030517578
2024-10-10 Close:238.77000427246094
2024-10-11 Close:217.8000030517578
2024-10-14 Close:219.16000366210938
2024-10-15 Close:219.57000732421875
2024-10-16 Close:221.3300018310547
2024-10-17 Close:220.88999938964844
2024-10-18 Close:220.6999969482422
2024-10-21 Close:218.85000610351562
2024-10-22 Close:217.97000122070312
2024-10-23 Close:213.64999389648438
2024-10-24 Close:260.4800109863281
2024-10-25 Close:269.19000244140625
2024-10-28 Close:262.510009765625
2024-10-29 Close:259.5199890136719
2024-10-30 Close:257.54998779296875
2024-10-31 Close:249.85000610351562
2024-11-01 Close:248.97999572753906
2024-11-04 Close:242.83999633789062
2024-11-05 Close:251.44000244140625
2024-11-06 Close:288.5299987792969
2024-11-07 Close:296.9100036621094
2024-11-08 Close:321.2200012207031
2024-11-11 Close:350.0
2024-11-12 Close:328.489990234375
2024-11-13 Close:330.239990234375
2024-11-14 Close:311.17999267578125
2024-11-15 Close:320.7200012207031
2024-11-18 Close:338.739990234375
2024-11-19 Close:346.0
2024-11-20 Close:342.0299987792969
2024-11-21 Close:339.6400146484375
2024-11-22 Close:352.55999755859375
2024-11-25 Close:338.5899963378906
2024-11-26 Close:338.2300109863281
2024-11-27 Close:332.8900146484375
2024-11-29 Close:345.1600036621094
2024-12-02 Close:357.0899963378906
2024-12-03 Close:351.4200134277344
2024-12-04 Close:357.92999267578125
2024-12-05 Close:369.489990234375
2024-12-06 Close:389.2200012207031
2024-12-09 Close:389.7900085449219
2024-12-10 Close:400.989990234375
2024-12-11 Close:424.7699890136719
2024-12-12 Close:418.1000061035156
2024-12-13 Close:436.2300109863281
2024-12-16 Close:463.0199890136719
2024-12-17 Close:479.8599853515625
2024-12-18 Close:440.1300048828125
2024-12-19 Close:436.1700134277344
2024-12-20 Close:421.05999755859375
2024-12-23 Close:430.6000061035156
2024-12-24 Close:462.2799987792969
2024-12-26 Close:454.1300048828125
2024-12-27 Close:431.6600036621094
2024-12-30 Close:417.4100036621094
2024-12-31 Close:403.8399963378906
2025-01-02 Close:379.2799987792969
2025-01-03 Close:410.44000244140625
2025-01-06 Close:411.04998779296875
2025-01-07 Close:394.3599853515625
2025-01-08 Close:394.94000244140625
2025-01-10 Close:394.739990234375
2025-01-13 Close:403.30999755859375
2025-01-14 Close:396.3599853515625
2025-01-15 Close:428.2200012207031
2025-01-16 Close:413.82000732421875
2025-01-17 Close:426.5
2025-01-21 Close:424.07000732421875
2025-01-22 Close:415.1099853515625
2025-01-23 Close:412.3800048828125
2025-01-24 Close:406.5799865722656
2025-01-27 Close:397.1499938964844
2025-01-28 Close:398.0899963378906
2025-01-29 Close:389.1000061035156
2025-01-30 Close:400.2799987792969
2025-01-31 Close:404.6000061035156
2025-02-03 Close:383.67999267578125
2025-02-04 Close:392.2099914550781
2025-02-05 Close:378.1700134277344
2025-02-06 Close:374.32000732421875
2025-02-07 Close:361.6199951171875
2025-02-10 Close:350.7300109863281
2025-02-11 Close:328.5
2025-02-12 Close:336.510009765625
2025-02-13 Close:355.94000244140625
2025-02-14 Close:355.8399963378906
2025-02-18 Close:354.1099853515625
2025-02-19 Close:360.55999755859375
2025-02-20 Close:354.3999938964844
2025-02-21 Close:337.79998779296875
2025-02-24 Close:330.5299987792969
2025-02-25 Close:302.79998779296875
2025-02-26 Close:290.79998779296875
2025-02-27 Close:281.95001220703125
2025-02-28 Close:292.9800109863281
2025-03-03 Close:284.6499938964844
2025-03-04 Close:272.0400085449219
2025-03-05 Close:279.1000061035156
2025-03-06 Close:263.45001220703125
2025-03-07 Close:262.6700134277344
2025-03-10 Close:222.14999389648438
2025-03-11 Close:230.5800018310547
2025-03-12 Close:248.08999633789062
2025-03-13 Close:240.67999267578125
2025-03-14 Close:249.97999572753906
2025-03-17 Close:238.00999450683594
2025-03-18 Close:225.30999755859375
2025-03-19 Close:235.86000061035156
2025-03-20 Close:236.25999450683594
2025-03-21 Close:248.7100067138672
2025-03-24 Close:278.3900146484375
2025-03-25 Close:288.1400146484375
2025-03-26 Close:272.05999755859375
2025-03-27 Close:273.1300048828125
2025-03-28 Close:263.54998779296875
2025-03-31 Close:259.1600036621094
2025-04-01 Close:268.4599914550781
2025-04-02 Close:282.760009765625
2025-04-03 Close:267.2799987792969
2025-04-04 Close:239.42999267578125
2025-04-07 Close:233.2899932861328
2025-04-08 Close:221.86000061035156
2025-04-09 Close:272.20001220703125
2025-04-10 Close:252.39999389648438
2025-04-11 Close:252.30999755859375
2025-04-14 Close:252.35000610351562

From this point on, the structure of our script will mostly remain the same and we will write the bulk of our strategies under the next function of the Strategy class.

## How to run a bactest using Backtrader

We will test out a moving average crossover strategy. Essentially, it involves monitoring two moving averages and taking a trade when one crosses the other.

The moving average crossover strategy is to trading what the Hello World script is to programming. Neither will likely ever be used in the real world and are mostly used for illustrative purposes. In other words, we don’t expect the strategy to be a profitable one.

There are a few things we will do before diving into the strategy. First, we will separate our strategy into its own file. Throughout this tutorial, we will go over several examples and separating out the strategies from the main script will keep the code in a nice clean format.

The main script, which will have everything cerebro related, will only have minor changes throughout the tutorial while most of the work will be done in the strategies script.

We also have to separate our data into two parts. This way, we can test our strategy on the first part, run some optimization, and then see how it performs with our optimized parameters on the second set of data.

If you’ve heard the terms in-sample data, or out-of-sample data, this is what it is referring to. Out-of-sample data is simply data set aside for testing after optimization.

There are a lot of benefits to testing and optimizing this way, take a look at What is a Walk-Forward Optimization and How to Run It? if you’d like to get a more thorough understanding of the methodology.

To divide the data, we set a from date and to date when loading our data. Don’t forget to import the DateTime module for this part.

## "Refer to main.py and strategy2.py file in the github repo for bactrader "

## How to build a stock screener in Backtrader

Screeners are commonly used to filter out stocks based on certain parameters. There aren’t a lot of easy ways to look back to a certain date and see what results a stock screener might have spit out. Fortunately, Backtrader offers exactly this

We will test out this functionality by building a screener that filters out stocks that are trading two standad devation below the average price over the prior 20 days

In [8]:
import backtrader as bt 
class Screener_SMA(bt.Analyzer):
    params = (('period',20),
              ('devfactor',2),)
    def start(self):
        self.bband = {
            data : bt.indicators.BollingerBands(data,period = self.params.period , devfactor = self.params.devfactor)
            for data in self.datas
        } # dictionary made for data and bband 
    
    def stop(self):
        self.rets['over'] = list()
        self.rets['under'] = list()

        for data ,band in self.bband.items():
            node = data._name , data.close[0] , round(band.lines.bot[0],2)
            # band.lines.bot[0] gives the MA-2SD for current data 
            if data > band.lines.bot :
                self.rets['over'].append(node)
            else:
                self.rets['under'].append(node)

Under the start function, you’ll notice that we are using Bollinger bands to determine the value for two standard deviations. The syntax is a bit different from prior examples as several datasets are used in a screener.

The stop function is where a bulk of our code falls. We iterate through our Bollinger band items for all of our datasets to filter out the ones that are trading below the lower band.

The stocks that qualify then get appended to a list. The analyzer class has a built-in dictionary with the variable name rets. We will use this dictionary to store our lists.

There isn’t a lot of code required in our main script, but it is quite different from prior examples. Since we are adding several datasets, we’ve created a list of all the tickers that we want to scan. We then iterate through the list to add the corresponding CSV files to cerebro.

The writer=True parameter calls the built-in writer functionality to display the ouput. stdstats=False removes some of the standard output (more on this later). And lastly, runonce=False ensures that data remains synchronized.

In [9]:
import datetime
import backtrader as bt

#Instantiate Cerebro engine
cerebro = bt.Cerebro()

#Add data to Cerebro
instruments = ['TSLA', 'AAPL', 'GE', 'GRPN','RELIANCE.NS','INFY']
for ticker in instruments:
    start = datetime.datetime(2025,1,1)
    end = datetime.datetime(2026,7,8)
    df = yf.download(ticker,start,end)
    df.columns = df.columns.droplevel(1)
    df.to_csv(f'{ticker}.csv')
    data = bt.feeds.GenericCSVData(
        dataname = f'{ticker}.csv',
        dtformat='%Y-%m-%d', # Ensure this matches the date format in your CSV (e.g., YYYY-MM-DD)
        datetime=0,
        open=4,
        high=2,
        low=3,
        close=1,
        volume=5,
        openinterest=-1,
        headers=True)
    cerebro.adddata(data) 

#Add analyzer for screener
cerebro.addanalyzer(Screener_SMA)

if __name__ == '__main__':
    #Run Cerebro Engine
    cerebro.run(runonce=False, stdstats=False, writer=True)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

===============================================================================
Cerebro:
  -----------------------------------------------------------------------------
  - Datas:
    +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    - Data0:
      - Name: TSLA
      - Timeframe: Days
      - Compression: 1
    +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    - Data1:
      - Name: AAPL
      - Timeframe: Days
      - Compression: 1
    +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    - Data2:
      - Name: GE
      - Timeframe: Days
      - Compression: 1
    +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    - Data3:
      - Name: GRPN
      - Timeframe: Days
      - Compression: 1
    +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    - Data4:
      - Name: RELIANCE.NS
      - Timeframe: Days
      - Compression: 1
    +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    - Data5:
      - Name: INFY
      - Timeframe: Days
      - Compression: 1
  -----------------------------------------------------------------------------
  - Strategies:
    +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    - Strategy:
      *************************************************************************
      - Params:
      *************************************************************************
      - Indicators:
        .......................................................................
        - BollingerBands:
          - Lines: mid, top, bot
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          - Params:
            - period: 20
            - devfactor: 2
            - movav: MovingAverageSimple
      *************************************************************************
      - Observers:
      *************************************************************************
      - Analyzers:
        .......................................................................
        - Value:
          - Begin: 10000.0
          - End: 10000.0
        .......................................................................
        - screener_sma:
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          - Params:
            - period: 20
            - devfactor: 2
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          - Analysis:
            - over: ('TSLA', 402.8999938964844, 370.59), ('AAPL', 310.6600036621094, 277.16), ('GE', 366.9800109863281, 317.82), ('GRPN', 26.850000381469727, 11.98), ('RELIANCE.NS', 1308.4000244140625, 1269.52), ('INFY', 11.270000457763672, 10.14)
            - under:

## How to code an indicator in backtrader

There are three ways to use an indicator in backtrader.

* you can use inbuilt indicator
 
* use a third party library 

* you can code from scratch

Here We are gonna code ATR (Volatility Indicator) for our case

In [10]:
class AverageTrueRange(bt.Strategy):
    def log(self,txt,dt=None):
        dt = dt or self.datas[0].datetime.date(0)
        print(f'{dt.isoformat()} {txt}') # print data and close 

    def __init__(self):
        self.dataclose = self.datas[0].close
        self.datahigh = self.datas[0].high
        self.datalow = self.datas[0].low
    
    def next(self):
        range_total = 0
        
        for i in range(-13,1):
            true_range = self.datahigh[i] - self.datalow[i]

            range_total += true_range
        
        ATR = range_total / 14 

        self.log(f'Close: {self.dataclose[0]:.2f},ATR: {ATR:.4f}')


cerebro = bt.Cerebro()
data = bt.feeds.GenericCSVData(
        dataname = 'TSLA.csv',
        dtformat='%Y-%m-%d',
        # setting fot testing data 
        fromdate = datetime.datetime(2024,1,1),
        todate = datetime.datetime(2026,1,1),
        datetime=0,
        open=4,
        high=2,
        low=3,
        close=1,
        volume=5,
        openinterest = -1,
        headers = True
    )
cerebro.adddata(data)
cerebro.addstrategy(AverageTrueRange)

cerebro.run()

2025-01-02 Close: 379.28,ATR: 15.8814
2025-01-03 Close: 410.44,ATR: 16.6736
2025-01-06 Close: 411.05,ATR: 17.4321
2025-01-07 Close: 394.36,ATR: 17.3364
2025-01-08 Close: 394.94,ATR: 16.3379
2025-01-10 Close: 394.74,ATR: 16.6414
2025-01-13 Close: 403.31,ATR: 17.2093
2025-01-14 Close: 396.36,ATR: 18.2521
2025-01-15 Close: 428.22,ATR: 19.3243
2025-01-16 Close: 413.82,ATR: 19.3793
2025-01-17 Close: 426.50,ATR: 19.7164
2025-01-21 Close: 424.07,ATR: 20.8943
2025-01-22 Close: 415.11,ATR: 21.1886
2025-01-23 Close: 412.38,ATR: 21.5121
2025-01-24 Close: 406.58,ATR: 21.0414
2025-01-27 Close: 397.15,ATR: 19.9886
2025-01-28 Close: 398.09,ATR: 19.2286
2025-01-29 Close: 389.10,ATR: 18.4986
2025-01-30 Close: 400.28,ATR: 19.4264
2025-01-31 Close: 404.60,ATR: 19.1879
2025-02-03 Close: 383.68,ATR: 18.5514
2025-02-04 Close: 392.21,ATR: 17.4443
2025-02-05 Close: 378.17,ATR: 16.6386
2025-02-06 Close: 374.32,ATR: 16.4493
2025-02-07 Close: 361.62,ATR: 16.4650
2025-02-10 Close: 350.73,ATR: 15.4150
2025-02-11 Close: 328.50,ATR: 16.1907
2025-02-12 Close: 336.51,ATR: 16.5836
2025-02-13 Close: 355.94,ATR: 16.7793
2025-02-14 Close: 355.84,ATR: 16.5514
2025-02-18 Close: 354.11,ATR: 16.1936
2025-02-19 Close: 360.56,ATR: 16.1621
2025-02-20 Close: 354.40,ATR: 15.1771
2025-02-21 Close: 337.80,ATR: 15.3136
2025-02-24 Close: 330.53,ATR: 15.5200
2025-02-25 Close: 302.80,ATR: 16.8800
2025-02-26 Close: 290.80,ATR: 17.4586
2025-02-27 Close: 281.95,ATR: 17.7536
2025-02-28 Close: 292.98,ATR: 17.7586
2025-03-03 Close: 284.65,ATR: 18.7907
2025-03-04 Close: 272.04,ATR: 18.6650
2025-03-05 Close: 279.10,ATR: 18.2764
2025-03-06 Close: 263.45,ATR: 18.0471
2025-03-07 Close: 262.67,ATR: 18.1200
2025-03-10 Close: 222.15,ATR: 19.8550
2025-03-11 Close: 230.58,ATR: 20.3100
2025-03-12 Close: 248.09,ATR: 20.0557
2025-03-13 Close: 240.68,ATR: 19.7079
2025-03-14 Close: 249.98,ATR: 19.2186
2025-03-17 Close: 238.01,ATR: 17.8586
2025-03-18 Close: 225.31,ATR: 16.9200
2025-03-19 Close: 235.86,ATR: 16.6243
2025-03-20 Close: 236.26,ATR: 15.7436
2025-03-21 Close: 248.71,ATR: 14.9100
2025-03-24 Close: 278.39,ATR: 14.8957
2025-03-25 Close: 288.14,ATR: 15.2586
2025-03-26 Close: 272.06,ATR: 15.6700
2025-03-27 Close: 273.13,ATR: 15.9921
2025-03-28 Close: 263.55,ATR: 14.7179
2025-03-31 Close: 259.16,ATR: 14.5150
2025-04-01 Close: 268.46,ATR: 15.0479
2025-04-02 Close: 282.76,ATR: 16.3357
2025-04-03 Close: 267.28,ATR: 16.6171
2025-04-04 Close: 239.43,ATR: 17.5029
2025-04-07 Close: 233.29,ATR: 19.6407
2025-04-08 Close: 221.86,ATR: 21.1000
2025-04-09 Close: 272.20,ATR: 24.1614
2025-04-10 Close: 252.40,ATR: 24.7464
2025-04-11 Close: 252.31,ATR: 24.3229
2025-04-14 Close: 252.35,ATR: 24.2479
2025-04-15 Close: 254.11,ATR: 23.7350
2025-04-16 Close: 241.55,ATR: 23.5957
2025-04-17 Close: 241.37,ATR: 22.9621
2025-04-21 Close: 227.50,ATR: 22.4064
2025-04-22 Close: 237.97,ATR: 22.0307
2025-04-23 Close: 250.74,ATR: 20.6950
2025-04-24 Close: 259.51,ATR: 20.3771
2025-04-25 Close: 284.95,ATR: 20.5357
2025-04-28 Close: 285.88,ATR: 19.4421
2025-04-29 Close: 292.03,ATR: 18.1000
2025-04-30 Close: 282.16,ATR: 15.4471
2025-05-01 Close: 280.52,ATR: 14.5829
2025-05-02 Close: 287.21,ATR: 14.4821
2025-05-05 Close: 280.26,ATR: 14.0950
2025-05-06 Close: 275.35,ATR: 13.7500
2025-05-07 Close: 276.22,ATR: 12.9529
2025-05-08 Close: 284.82,ATR: 13.2193
2025-05-09 Close: 298.26,ATR: 13.7636
2025-05-12 Close: 318.38,ATR: 13.6043
2025-05-13 Close: 334.07,ATR: 14.0164
2025-05-14 Close: 347.68,ATR: 14.2064
2025-05-15 Close: 342.82,ATR: 13.0779
2025-05-16 Close: 349.98,ATR: 12.1386
2025-05-19 Close: 342.09,ATR: 11.8371
2025-05-20 Close: 343.82,ATR: 11.8150
2025-05-21 Close: 334.62,ATR: 12.1071
2025-05-22 Close: 341.04,ATR: 12.1721
2025-05-23 Close: 339.34,ATR: 12.1379
2025-05-27 Close: 362.89,ATR: 12.8586
2025-05-28 Close: 356.90,ATR: 13.0136
2025-05-29 Close: 358.43,ATR: 13.1079
2025-05-30 Close: 346.46,ATR: 13.2043
2025-06-02 Close: 342.69,ATR: 13.4886
2025-06-03 Close: 344.27,ATR: 12.8864
2025-06-04 Close: 332.05,ATR: 13.2629
2025-06-05 Close: 284.70,ATR: 16.1143
2025-06-06 Close: 295.14,ATR: 16.4764
2025-06-09 Close: 308.58,ATR: 17.7871
2025-06-10 Close: 326.09,ATR: 18.0586
2025-06-11 Close: 326.43,ATR: 17.9050
2025-06-12 Close: 319.11,ATR: 17.8921
2025-06-13 Close: 325.31,ATR: 18.5864
2025-06-16 Close: 329.13,ATR: 17.8129
2025-06-17 Close: 316.35,ATR: 18.0579
2025-06-18 Close: 322.05,ATR: 18.2121
2025-06-20 Close: 322.16,ATR: 17.9400
2025-06-23 Close: 348.68,ATR: 19.0379
2025-06-24 Close: 340.47,ATR: 19.2850
2025-06-25 Close: 327.55,ATR: 19.5943
2025-06-26 Close: 325.78,ATR: 16.4586
2025-06-27 Close: 323.63,ATR: 16.2786
2025-06-30 Close: 317.66,ATR: 14.9214
2025-07-01 Close: 300.71,ATR: 14.6014
2025-07-02 Close: 315.65,ATR: 14.6021
2025-07-03 Close: 315.35,ATR: 13.8871
2025-07-07 Close: 293.94,ATR: 13.0079
2025-07-08 Close: 297.81,ATR: 13.2979
2025-07-09 Close: 295.88,ATR: 12.8750
2025-07-10 Close: 309.87,ATR: 12.6329
2025-07-11 Close: 313.51,ATR: 12.1943
2025-07-14 Close: 316.90,ATR: 10.7564
2025-07-15 Close: 310.78,ATR: 10.3907
2025-07-16 Close: 321.67,ATR: 9.5536
2025-07-17 Close: 319.41,ATR: 9.5421
2025-07-18 Close: 329.65,ATR: 9.3736
2025-07-21 Close: 328.49,ATR: 9.5264
2025-07-22 Close: 332.11,ATR: 9.6107
2025-07-23 Close: 332.56,ATR: 9.2193
2025-07-24 Close: 305.30,ATR: 9.5086
2025-07-25 Close: 316.06,ATR: 10.0971
2025-07-28 Close: 325.59,ATR: 10.4614
2025-07-29 Close: 321.20,ATR: 10.5614
2025-07-30 Close: 319.04,ATR: 10.7293
2025-07-31 Close: 308.27,ATR: 11.2171
2025-08-01 Close: 302.63,ATR: 11.3286
2025-08-04 Close: 309.26,ATR: 11.2157
2025-08-05 Close: 308.72,ATR: 10.9350
2025-08-06 Close: 319.91,ATR: 11.3821
2025-08-07 Close: 322.27,ATR: 11.1507
2025-08-08 Close: 329.65,ATR: 11.3686
2025-08-11 Close: 339.03,ATR: 11.2707
2025-08-12 Close: 340.84,ATR: 11.6129
2025-08-13 Close: 339.38,ATR: 11.6871
2025-08-14 Close: 335.58,ATR: 11.2907
2025-08-15 Close: 330.56,ATR: 11.1107
2025-08-18 Close: 335.16,ATR: 11.0164
2025-08-19 Close: 329.31,ATR: 11.0071
2025-08-20 Close: 323.90,ATR: 11.1143
2025-08-21 Close: 320.11,ATR: 10.7379
2025-08-22 Close: 340.01,ATR: 11.5550
2025-08-25 Close: 346.60,ATR: 12.0943
2025-08-26 Close: 351.67,ATR: 11.7114
2025-08-27 Close: 349.60,ATR: 11.7107
2025-08-28 Close: 345.98,ATR: 11.6479
2025-08-29 Close: 333.87,ATR: 11.9736
2025-09-02 Close: 329.36,ATR: 11.6457
2025-09-03 Close: 334.09,ATR: 11.9343
2025-09-04 Close: 338.53,ATR: 11.7443
2025-09-05 Close: 350.84,ATR: 11.6664
2025-09-08 Close: 346.40,ATR: 12.1607
2025-09-09 Close: 346.97,ATR: 11.7500
2025-09-10 Close: 347.79,ATR: 11.2850
2025-09-11 Close: 368.81,ATR: 12.3686
2025-09-12 Close: 395.94,ATR: 12.7893
2025-09-15 Close: 410.04,ATR: 13.4157
2025-09-16 Close: 421.62,ATR: 13.6757
2025-09-17 Close: 425.86,ATR: 14.5621
2025-09-18 Close: 416.85,ATR: 14.7314
2025-09-19 Close: 426.07,ATR: 14.0671
2025-09-22 Close: 434.21,ATR: 14.6471
2025-09-23 Close: 425.85,ATR: 14.8207
2025-09-24 Close: 442.79,ATR: 15.3757
2025-09-25 Close: 423.39,ATR: 15.7386
2025-09-26 Close: 440.40,ATR: 16.1564
2025-09-29 Close: 443.21,ATR: 16.4800
2025-09-30 Close: 444.72,ATR: 16.5957
2025-10-01 Close: 459.46,ATR: 16.6064
2025-10-02 Close: 436.00,ATR: 17.2300
2025-10-03 Close: 429.83,ATR: 17.7243
2025-10-06 Close: 453.25,ATR: 18.0843
2025-10-07 Close: 433.09,ATR: 18.1979
2025-10-08 Close: 438.69,ATR: 18.2293
2025-10-09 Close: 435.54,ATR: 18.4021
2025-10-10 Close: 413.49,ATR: 19.5329
2025-10-13 Close: 435.90,ATR: 19.5286
2025-10-14 Close: 429.24,ATR: 19.6114
2025-10-15 Close: 435.15,ATR: 19.4621
2025-10-16 Close: 428.75,ATR: 19.3614
2025-10-17 Close: 439.31,ATR: 19.8171
2025-10-20 Close: 447.43,ATR: 19.6250
2025-10-21 Close: 442.60,ATR: 18.6043
2025-10-22 Close: 438.97,ATR: 17.2729
2025-10-23 Close: 448.98,ATR: 17.6521
2025-10-24 Close: 433.72,ATR: 17.9843
2025-10-27 Close: 452.42,ATR: 18.0729
2025-10-28 Close: 460.55,ATR: 18.0229
2025-10-29 Close: 461.51,ATR: 18.2286
2025-10-30 Close: 440.10,ATR: 17.0693
2025-10-31 Close: 456.56,ATR: 16.8636
2025-11-03 Close: 468.37,ATR: 17.1443
2025-11-04 Close: 444.26,ATR: 17.3186
2025-11-05 Close: 462.07,ATR: 17.8600
2025-11-06 Close: 445.91,ATR: 18.8957
2025-11-07 Close: 429.52,ATR: 19.4879
2025-11-10 Close: 445.23,ATR: 20.1350
2025-11-11 Close: 439.62,ATR: 19.6771
2025-11-12 Close: 430.60,ATR: 18.2679
2025-11-13 Close: 401.99,ATR: 18.7429
2025-11-14 Close: 404.35,ATR: 19.3100
2025-11-17 Close: 408.92,ATR: 20.0114
2025-11-18 Close: 401.25,ATR: 20.1643
2025-11-19 Close: 403.99,ATR: 20.0093
2025-11-20 Close: 395.23,ATR: 21.4300
2025-11-21 Close: 391.09,ATR: 21.3421
2025-11-24 Close: 417.78,ATR: 21.6286
2025-11-25 Close: 419.40,ATR: 20.8364
2025-11-26 Close: 426.58,ATR: 19.2429
2025-11-28 Close: 430.17,ATR: 18.4750
2025-12-01 Close: 430.14,ATR: 17.9079
2025-12-02 Close: 429.24,ATR: 18.2329
2025-12-03 Close: 446.74,ATR: 18.3071
2025-12-04 Close: 454.53,ATR: 16.9557
2025-12-05 Close: 455.00,ATR: 15.3700
2025-12-08 Close: 439.58,ATR: 14.6043
2025-12-09 Close: 445.17,ATR: 14.7114
2025-12-10 Close: 451.45,ATR: 14.7107
2025-12-11 Close: 446.89,ATR: 12.9064
2025-12-12 Close: 458.96,ATR: 13.0707
2025-12-15 Close: 475.31,ATR: 12.6050
2025-12-16 Close: 489.88,ATR: 13.4007
2025-12-17 Close: 467.26,ATR: 14.7600
2025-12-18 Close: 483.37,ATR: 15.5464
2025-12-19 Close: 481.20,ATR: 16.0750
2025-12-22 Close: 488.73,ATR: 15.9907
2025-12-23 Close: 485.56,ATR: 15.4421
2025-12-24 Close: 485.40,ATR: 15.7893
2025-12-26 Close: 475.19,ATR: 16.3650
2025-12-29 Close: 459.64,ATR: 16.0721
2025-12-30 Close: 454.43,ATR: 15.5436
2025-12-31 Close: 449.72,ATR: 15.1136

## How to plot in backtrader

To plot the chart in Backtrader is incredibly simple. All you need to do is add cerebro.plot() to your code after calling cerebro.run()

By default, the chart will attempt to show the following

* Fluctuations in your balance
* The profit or loss of any trades taken during the backtest
* Where buy and sell trades took place relative to the price.

If you’re not interested in seeing all of these additional details, simply pass through the following parameter – stdstats=False

If you’re working with two different stocks, you can easily show both on one chart. This can be useful if you’re trying to visualize the correlation between two assets.

In [11]:
import matplotlib.pyplot as plt #backtrader uses matplotlib you don't need to import this but i am doing so that i can get my graphs right below my code for reference 

%matplotlib widget

In [12]:
import datetime as dt
import backtrader as bt 

# initiate Cerebro Engine 
cerebro = bt.Cerebro(stdstats = False)

# set data parameters and add to Cerebro
data1 = bt.feeds.GenericCSVData(
        dataname = 'TSLA.csv',
        dtformat='%Y-%m-%d',
        # setting fot testing data 
        fromdate = datetime.datetime(2024,1,1),
        todate = datetime.datetime(2026,1,1),
        datetime=0,
        open=4,
        high=2,
        low=3,
        close=1,
        volume=5,
        openinterest = -1,
        headers = True
    )
cerebro.adddata(data1)

data2 = bt.feeds.GenericCSVData(
        dataname = 'AAPL.csv',
        dtformat='%Y-%m-%d',
        # setting fot testing data 
        fromdate = datetime.datetime(2024,1,1),
        todate = datetime.datetime(2026,1,1),
        datetime=0,
        open=4,
        high=2,
        low=3,
        close=1,
        volume=5,
        openinterest = -1,
        headers = True
    )


data2.compensate(data1) # let the system know ops on data1 affect data2
data2.plotinfo.plotmaster = data1
data2.plotinfo.sameaxis = True

cerebro.adddata(data2)

cerebro.run()
cerebro.plot()

[[<Figure size 640x480 with 3 Axes>]]

self.sma = bt.indicators.SimpleMovingAverage(self.data, period=20, 
                plotname="20 SMA")

Notice we passed through a value for plotname. It allows us to change the display value for the moving average in the legend.

## How to use Alternative Data in backtrader /

In this strategy, we’re going to try and gauge sentiment based on google search data, and execute trades based on any notable shifts in search volume.

We’ve downloaded historical weekly search data from Google Trends for Bitcoin and have obtained price data from Yahoo Finance.

In [13]:
import pandas as pd

In [14]:
bitcoin_close = pd.read_csv('Bitcoinclose.csv',parse_dates=True,index_col=0)
bitcoin_close
bitcoin_sentiment = pd.read_csv('BTC_Gtrands.csv',parse_dates=True,index_col=0)

In [15]:
bitcoin_close.head()

                   Close
Date
2021-07-01  41626.195312
2021-08-01  47166.687500
2021-09-01  43790.894531
2021-10-01  61318.957031
2021-11-01  57005.425781

In [16]:
bitcoin_sentiment.head()

            Bitcoin
Date
2021-07-01       62
2021-08-01       64
2021-09-01       61
2021-10-01       77
2021-11-01       71

In [17]:
bitcoin_merged = bitcoin_close.merge(bitcoin_sentiment,on='Date')
bitcoin_merged.to_csv('Bitcoin_merged.csv')

In [18]:
bitcoin_merged.head()

                   Close  Bitcoin
Date
2021-07-01  41626.195312       62
2021-08-01  47166.687500       64
2021-09-01  43790.894531       61
2021-10-01  61318.957031       77
2021-11-01  57005.425781       71

In [19]:
class CustomCSVData(bt.feeds.GenericCSVData):
    # Tell Backtrader to expect a new custom line
    lines = ('Bitcoin',)
    # Set a default column index for it
    params = (('Bitcoin', -1),)

data2 = CustomCSVData(
    dataname = 'Bitcoin_merged.csv',
    separator = ',',
    nullvalue = 0.0,
    dtformat=('%Y-%m-%d'),
    datetime = 0,
    time = -1,
    high = -1,
    close = 1,
    openinterest = -1,
    open = -1,
    Bitcoin = 2,
    low = -1,
    volume = -1,
    headers = True,
    timeframe = bt.TimeFrame.Months)

cerebro = bt.Cerebro()

cerebro.adddata(data2)



class BtcSentiment(bt.Strategy):
    params = (('period',10),('devfactor',1))

    def log(self,txt,dt=None):
        dt = dt or self.datas[0].datetime.date(0)
        print(f'{dt.isoformat()} {txt}')
    
    def __init__(self):
        self.btc_price = self.datas[0].close
        self.google_sentiment = self.datas[0].Bitcoin
        self.bbands = bt.indicators.BollingerBands(self.google_sentiment,period=self.params.period,devfactor = self.params.devfactor)
        self.order = None

    def notify_order(self,order):
        if order.status in [order.Submitted,order.Accepted]:
            return
        if order.status in [order.Completed]:
            if order.isbuy():
                self.log(f'BUY EXCEUTED, {order.executed.price:.2f}')
            elif order.issell():
                self.log(f'SELL EXCEUTED, {order.executed.price:.2f}')
        elif order.status in [order.Canceled , order.Margin, order.Rejected]:
            self.log('Order Canceled/Margin/Rejected')
        
        self.order = None

    def next(self):
        if self.order:
            return
        #long signal
        if self.google_sentiment[0] > self.bbands.lines.top[0]:
            if not self.position:
                self.log(f'Google Sentiment Value: {self.google_sentiment[0]:.2f}')
                self.log(f'Top band: {self.bbands.lines.top[0]:.2f}')
                # We are not in the market, we will open a trade
                self.log(f'***BUY CREATE {self.btc_price[0]:.2f}')
                # Keep track of the created order to avoid a 2nd order
                self.order = self.buy()
        #short signal
        elif self.google_sentiment[0] < self.bbands.lines.bot[0]:
            if not self.position:
                self.log(f'Google Sentiment Value: {self.google_sentiment[0]:.2f}')
                self.log(f'Bottom band: {self.bbands.lines.bot[0]:.2f}')
                # We are not in the market, we will open a trade
                self.log(f'***SELL CREATE {self.btc_price[0]:.2f}')
                # Keep track of the created order to avoid a 2nd order
                self.order = self.sell()
        # neutral position
        else:
            if self.position:
                self.log(f'Google Sentiment Value: {self.google_sentiment[0]:.2f}')
                self.log(f'Bottom band: {self.bbands.lines.bot[0]:.2f}')
                self.log(f'Top band: {self.bbands.lines.top[0]:.2f}')
                self.log(f'CLOSE CREATE {self.btc_price[0]:.2f}')
                self.order = self.close()
                

cerebro.addstrategy(BtcSentiment)
cerebro.addsizer(bt.sizers.FixedSize, stake=1)
cerebro.broker.setcash(100000)
cerebro.run()
print(cerebro.broker.getvalue())
print(f'NET PnL {cerebro.broker.getvalue()-100000}')

2022-04-01 Google Sentiment Value: 51.00
2022-04-01 Bottom band: 58.88
2022-04-01 ***SELL CREATE 37714.88
2022-05-01 SELL EXCEUTED, -0.00
2022-05-01 Google Sentiment Value: 73.00
2022-05-01 Bottom band: 60.15
2022-05-01 Top band: 78.85
2022-05-01 CLOSE CREATE 31792.31
2022-06-01 BUY EXCEUTED, 0.00
2022-06-01 Google Sentiment Value: 85.00
2022-06-01 Top band: 81.80
2022-06-01 ***BUY CREATE 19784.73
2022-07-01 BUY EXCEUTED, 0.00
2022-11-01 Google Sentiment Value: 52.00
2022-11-01 Bottom band: 44.68
2022-11-01 Top band: 73.52
2022-11-01 CLOSE CREATE 17168.57
2022-12-01 SELL EXCEUTED, -0.00
2022-12-01 Google Sentiment Value: 36.00
2022-12-01 Bottom band: 40.34
2022-12-01 ***SELL CREATE 16547.50
2023-01-01 SELL EXCEUTED, -0.00
2023-01-01 Google Sentiment Value: 43.00
2023-01-01 Bottom band: 38.13
2023-01-01 Top band: 67.87
2023-01-01 CLOSE CREATE 23139.28
2023-02-01 BUY EXCEUTED, 0.00
2023-02-01 Google Sentiment Value: 35.00
2023-02-01 Bottom band: 35.57
2023-02-01 ***SELL CREATE 23147.35
2023-03-01 SELL EXCEUTED, -0.00
2023-03-01 Google Sentiment Value: 48.00
2023-03-01 Bottom band: 34.80
2023-03-01 Top band: 63.00
2023-03-01 CLOSE CREATE 28478.48
2023-04-01 BUY EXCEUTED, 0.00
2023-09-01 Google Sentiment Value: 33.00
2023-09-01 Bottom band: 35.08
2023-09-01 ***SELL CREATE 26967.92
2023-10-01 SELL EXCEUTED, -0.00
2023-10-01 Google Sentiment Value: 40.00
2023-10-01 Bottom band: 35.63
2023-10-01 Top band: 43.97
2023-10-01 CLOSE CREATE 34667.78
2023-11-01 BUY EXCEUTED, 0.00
2023-12-01 Google Sentiment Value: 48.00
2023-12-01 Top band: 45.58
2023-12-01 ***BUY CREATE 42265.19
2024-01-01 BUY EXCEUTED, 0.00
2024-05-01 Google Sentiment Value: 49.00
2024-05-01 Bottom band: 36.70
2024-05-01 Top band: 69.70
2024-05-01 CLOSE CREATE 67491.41
2024-06-01 SELL EXCEUTED, -0.00
2024-11-01 Google Sentiment Value: 100.00
2024-11-01 Top band: 79.26
2024-11-01 ***BUY CREATE 96449.05
2024-12-01 BUY EXCEUTED, 0.00
2025-01-01 Google Sentiment Value: 70.00
2025-01-01 Bottom band: 40.28
2025-01-01 Top band: 80.12
2025-01-01 CLOSE CREATE 102405.02
2025-02-01 SELL EXCEUTED, -0.00
2025-11-01 Google Sentiment Value: 81.00
2025-11-01 Top band: 72.70
2025-11-01 ***BUY CREATE 90394.31
2025-12-01 BUY EXCEUTED, 0.00
2025-12-01 Google Sentiment Value: 64.00
2025-12-01 Bottom band: 50.61
2025-12-01 Top band: 73.19
2025-12-01 CLOSE CREATE 87508.83
2026-01-01 SELL EXCEUTED, -0.00
2026-02-01 Google Sentiment Value: 90.00
2026-02-01 Top band: 78.97
2026-02-01 ***BUY CREATE 66995.86
2026-03-01 BUY EXCEUTED, 0.00
2026-03-01 Google Sentiment Value: 62.00
2026-03-01 Bottom band: 53.08
2026-03-01 Top band: 79.32
2026-03-01 CLOSE CREATE 68233.31
2026-04-01 SELL EXCEUTED, -0.00
2026-04-01 Google Sentiment Value: 52.00
2026-04-01 Bottom band: 54.51
2026-04-01 ***SELL CREATE 76304.32
2026-05-01 SELL EXCEUTED, -0.00
2026-06-01 Google Sentiment Value: 53.00
2026-06-01 Bottom band: 49.97
2026-06-01 Top band: 76.03
2026-06-01 CLOSE CREATE 58558.86
41441.140625
NET PnL -58558.859375

We Lost Money by this Strategy but it doesn't mean that its not a good strategy before 2020 this strategy has created 60% return

## How to add Visual Stats to a backtest

Backtrader has quite a few analyzers that provide in-depth detail of the backtest. But rather than programming several analyzers, we can use a third-party library which will show complete statistics of the backtest as well as other visualizations.

A popular library for this is PyFolio which can create a detailed tearsheet with all sorts of information. This is done via Jupyter notebooks.

Another good option is to use the quantstats library. The benefit of this library is that it saves an HTML file of the stats, eliminating the additional step of running a notebook that PyFolio requires

Both quantstats and PyFolio require returns data to calculate stats. We can use a Backtrader analyzer to get this data.

We will build on our previous alternative data example and create a stats tearsheet from our BTC sentiment strategy. The first step is to add the analyzer that will give us returns data. We need to add the following line of code:

Spot the changes i have made from the previous code

We will build on our previous alternative data example and create a stats tearsheet from our BTC sentiment strategy. The first step is to add the analyzer that will give us returns data. We need to add the following line of code:

cerebro.addanalyzer(bt.analyzers.PyFolio, _name='PyFolio')

The above line of code can be added anywhere in the script as long as it’s before the cerebro.run command and after initializing the cerebro class.

As you may have guessed from the name, this analyzer was created to enable a PyFolio integration. But it works just as well with the quantstats library.

We will need to save the results from our backtest, similar to what we did in the Sharpe Ratio example.

results = cerebro.run()

strat = results[0]

At the end of our script, after our backtest completes, we can add some code to extract the returns data from the analyzer.

portfolio_stats = strat.analyzers.getbyname('PyFolio')
returns, positions, transactions, gross_lev = portfolio_stats.get_pf_items()
returns.index = returns.index.tz_convert(None)

The above code gets all the data obtained by the PyFolio analyzer. We then split the returned data to extract just the returns values.

As you may have guessed from the name, this analyzer was created to enThe returns variable is actually a Pandas DataFrame. To make it compatible with quantstats, we removed the timezone awareness using the built-in tz_convertfunction from Pandas.

Since we are using Pandas, we have to import it into our script. We can also import the quantstat library at the same time. We’ll add the following at the top of our script to do that.

import pandas as pd


import quantstats

Let’s jump back to the bottom of the script and add the functionality to create a stats tearsheet.

In [20]:
import quantstats

In [21]:
class CustomCSVData(bt.feeds.GenericCSVData):
    # Tell Backtrader to expect a new custom line
    lines = ('Bitcoin',)
    # Set a default column index for it
    params = (('Bitcoin', -1),)

data2 = CustomCSVData(
    dataname = 'Bitcoin_merged.csv',
    separator = ',',
    nullvalue = 0.0,
    dtformat=('%Y-%m-%d'),
    datetime = 0,
    time = -1,
    high = -1,
    close = 1,
    openinterest = -1,
    open = -1,
    Bitcoin = 2,
    low = -1,
    volume = -1,
    headers = True,
    timeframe = bt.TimeFrame.Months)

cerebro = bt.Cerebro()

cerebro.adddata(data2)
# Pyfolio integration for backtest Analysis 
cerebro.addanalyzer(bt.analyzers.PyFolio, _name='PyFolio')

class BtcSentiment(bt.Strategy):
    params = (('period',10),('devfactor',1))

    def log(self,txt,dt=None):
        dt = dt or self.datas[0].datetime.date(0)
        print(f'{dt.isoformat()} {txt}')
    
    def __init__(self):
        self.btc_price = self.datas[0].close
        self.google_sentiment = self.datas[0].Bitcoin
        self.bbands = bt.indicators.BollingerBands(self.google_sentiment,period=self.params.period,devfactor = self.params.devfactor)
        self.order = None

    def notify_order(self,order):
        if order.status in [order.Submitted,order.Accepted]:
            return
        if order.status in [order.Completed]:
            if order.isbuy():
                self.log(f'BUY EXCEUTED, {order.executed.price:.2f}')
            elif order.issell():
                self.log(f'SELL EXCEUTED, {order.executed.price:.2f}')
        elif order.status in [order.Canceled , order.Margin, order.Rejected]:
            self.log('Order Canceled/Margin/Rejected')
        
        self.order = None

    def next(self):
        if self.order:
            return
        #long signal
        if self.google_sentiment[0] > self.bbands.lines.top[0]:
            if not self.position:
                self.log(f'Google Sentiment Value: {self.google_sentiment[0]:.2f}')
                self.log(f'Top band: {self.bbands.lines.top[0]:.2f}')
                # We are not in the market, we will open a trade
                self.log(f'***BUY CREATE {self.btc_price[0]:.2f}')
                # Keep track of the created order to avoid a 2nd order
                self.order = self.buy()
        #short signal
        elif self.google_sentiment[0] < self.bbands.lines.bot[0]:
            if not self.position:
                self.log(f'Google Sentiment Value: {self.google_sentiment[0]:.2f}')
                self.log(f'Bottom band: {self.bbands.lines.bot[0]:.2f}')
                # We are not in the market, we will open a trade
                self.log(f'***SELL CREATE {self.btc_price[0]:.2f}')
                # Keep track of the created order to avoid a 2nd order
                self.order = self.sell()
        # neutral position
        else:
            if self.position:
                self.log(f'Google Sentiment Value: {self.google_sentiment[0]:.2f}')
                self.log(f'Bottom band: {self.bbands.lines.bot[0]:.2f}')
                self.log(f'Top band: {self.bbands.lines.top[0]:.2f}')
                self.log(f'CLOSE CREATE {self.btc_price[0]:.2f}')
                self.order = self.close()
                

cerebro.addstrategy(BtcSentiment)
cerebro.addsizer(bt.sizers.FixedSize, stake=1)
cerebro.broker.setcash(100000)
results = cerebro.run()
strat = results[0]
print(cerebro.broker.getvalue())
print(f'NET PnL {cerebro.broker.getvalue()-100000}')
portfolio_stats = strat.analyzers.getbyname('PyFolio')
returns, positions, transactions, gross_lev = portfolio_stats.get_pf_items()
returns.index = returns.index.tz_convert(None)   
quantstats.reports.html(returns, output='stats.html', title='BTC Sentiment')

2022-04-01 Google Sentiment Value: 51.00
2022-04-01 Bottom band: 58.88
2022-04-01 ***SELL CREATE 37714.88
2022-05-01 SELL EXCEUTED, -0.00
2022-05-01 Google Sentiment Value: 73.00
2022-05-01 Bottom band: 60.15
2022-05-01 Top band: 78.85
2022-05-01 CLOSE CREATE 31792.31
2022-06-01 BUY EXCEUTED, 0.00
2022-06-01 Google Sentiment Value: 85.00
2022-06-01 Top band: 81.80
2022-06-01 ***BUY CREATE 19784.73
2022-07-01 BUY EXCEUTED, 0.00
2022-11-01 Google Sentiment Value: 52.00
2022-11-01 Bottom band: 44.68
2022-11-01 Top band: 73.52
2022-11-01 CLOSE CREATE 17168.57
2022-12-01 SELL EXCEUTED, -0.00
2022-12-01 Google Sentiment Value: 36.00
2022-12-01 Bottom band: 40.34
2022-12-01 ***SELL CREATE 16547.50
2023-01-01 SELL EXCEUTED, -0.00
2023-01-01 Google Sentiment Value: 43.00
2023-01-01 Bottom band: 38.13
2023-01-01 Top band: 67.87
2023-01-01 CLOSE CREATE 23139.28
2023-02-01 BUY EXCEUTED, 0.00
2023-02-01 Google Sentiment Value: 35.00
2023-02-01 Bottom band: 35.57
2023-02-01 ***SELL CREATE 23147.35
2023-03-01 SELL EXCEUTED, -0.00
2023-03-01 Google Sentiment Value: 48.00
2023-03-01 Bottom band: 34.80
2023-03-01 Top band: 63.00
2023-03-01 CLOSE CREATE 28478.48
2023-04-01 BUY EXCEUTED, 0.00
2023-09-01 Google Sentiment Value: 33.00
2023-09-01 Bottom band: 35.08
2023-09-01 ***SELL CREATE 26967.92
2023-10-01 SELL EXCEUTED, -0.00
2023-10-01 Google Sentiment Value: 40.00
2023-10-01 Bottom band: 35.63
2023-10-01 Top band: 43.97
2023-10-01 CLOSE CREATE 34667.78
2023-11-01 BUY EXCEUTED, 0.00
2023-12-01 Google Sentiment Value: 48.00
2023-12-01 Top band: 45.58
2023-12-01 ***BUY CREATE 42265.19
2024-01-01 BUY EXCEUTED, 0.00
2024-05-01 Google Sentiment Value: 49.00
2024-05-01 Bottom band: 36.70
2024-05-01 Top band: 69.70
2024-05-01 CLOSE CREATE 67491.41
2024-06-01 SELL EXCEUTED, -0.00
2024-11-01 Google Sentiment Value: 100.00
2024-11-01 Top band: 79.26
2024-11-01 ***BUY CREATE 96449.05
2024-12-01 BUY EXCEUTED, 0.00
2025-01-01 Google Sentiment Value: 70.00
2025-01-01 Bottom band: 40.28
2025-01-01 Top band: 80.12
2025-01-01 CLOSE CREATE 102405.02
2025-02-01 SELL EXCEUTED, -0.00
2025-11-01 Google Sentiment Value: 81.00
2025-11-01 Top band: 72.70
2025-11-01 ***BUY CREATE 90394.31
2025-12-01 BUY EXCEUTED, 0.00
2025-12-01 Google Sentiment Value: 64.00
2025-12-01 Bottom band: 50.61
2025-12-01 Top band: 73.19
2025-12-01 CLOSE CREATE 87508.83
2026-01-01 SELL EXCEUTED, -0.00
2026-02-01 Google Sentiment Value: 90.00
2026-02-01 Top band: 78.97
2026-02-01 ***BUY CREATE 66995.86
2026-03-01 BUY EXCEUTED, 0.00
2026-03-01 Google Sentiment Value: 62.00
2026-03-01 Bottom band: 53.08
2026-03-01 Top band: 79.32
2026-03-01 CLOSE CREATE 68233.31
2026-04-01 SELL EXCEUTED, -0.00
2026-04-01 Google Sentiment Value: 52.00
2026-04-01 Bottom band: 54.51
2026-04-01 ***SELL CREATE 76304.32
2026-05-01 SELL EXCEUTED, -0.00
2026-06-01 Google Sentiment Value: 53.00
2026-06-01 Bottom band: 49.97
2026-06-01 Top band: 76.03
2026-06-01 CLOSE CREATE 58558.86
41441.140625
NET PnL -58558.859375

## How to save backtest data to a CSV file

In the examples here, we’ve printed opened and closed trades to the console. But if you’re running multiple tests and later want to compare them, it might be useful writing your backtest data to a CSV file.

There is a built-in method in backtrader that will create a CSV file for you. It includes data from your data feeds, strategies, indicators, and analyzers.

To use it, simply add the following line to your script. It can be added anywhere in the script as long as it is before cerebro.run and after instantiating the cerebro class.

```python
cerebro.addwriter(bt.WriterFile, csv=True, out='log.csv')

For the out parameter, we’ve specified log.csv. You can name the file anything you want. After running your backtest, there should be a CSV file in your projects directory with all of the earlier mentioned data.

There are other options as well if you’d like a more customized approach. Within the strategy class, we can overwrite the stop() function to save any variable within the class. Here is an example.

```python
class BtcSentiment(bt.Strategy):
	def __init__(self, sp):
		self.log_pnl = []
```

In the __init__ function, we’ve initialized a variable called log_pnl as a list.

```python
def log(self, txt, dt=None):
    dt = dt or self.datas[0].datetime.date(0)
    print(f'{dt.isoformat()} {txt}') #Print date and close
    self.log_pnl.append(f'{dt.isoformat()} {txt}')

```
Then under the log function, we’re appending the output (what would normally be printed to the console) to our log_pnl list.

Finally, we can save the list to a file once the backtest is finished running. For this, we use the stop() function which runs one time when the backtest is complete. Here is the code to save the log_pnl to file.

```python
def stop(self):
    with open('custom_log.csv', 'w') as e:
        for line in self.log_file:
            e.write(line + '\n')
```

You can use this method to save any custom data from backtrader to a file.

In our previous example, we used the backtrader PyFolio analyzer to generate returns and other data that took the form of a Pandas DataFrame. We can save the returns data, or any of the other files by using the built-in to_csv() method from Pandas.
```python
returns.to_csv('returns.csv'))

Lastly, the focus when it comes to strategy development should be to come up with a good foundation and then use optimization for minor tweaks. Sometimes traders fall into the trap of approaching it the other way around which rarely leads to a profitable strategy.